# Generated by Django 4.2 on 2023-04-25 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netcodeapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Codes',
            new_name='Code',
        ),
    ]
