# Generated by Django 4.2 on 2023-05-01 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netcodeapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='user',
        ),
    ]
