# Generated by Django 4.2 on 2023-05-19 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netcodeapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='picture',
            field=models.ImageField(blank=True, default='default.webp', null=True, upload_to='images'),
        ),
    ]
