# Generated by Django 4.2 on 2023-05-03 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netcodeapi', '0002_remove_code_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='created',
        ),
        migrations.RemoveField(
            model_name='code',
            name='updated',
        ),
    ]
