# Generated by Django 4.2 on 2023-05-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netcodeapi', '0003_remove_code_created_remove_code_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='created',
            field=models.DateField(auto_now_add=True, default='2023-05-03'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='code',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
